language: php

sudo: required
dist: trusty

php:
  - '7.1'

services:
  - postgresql


before_script:
  - psql -c 'create database ourhomework_testing;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - composer install --no-interaction
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.travis .env
  - php artisan serve > /dev/null 2>&1 &

script:
  - php artisan dusk
